### ISSUE TITLE
SPLADE

### ISSUE THREAD

**Issue by nickprock** [anakin87/neural-search-pills#1]
Hi @anakin87
Great job! When a pill on SPLADE?

**Comment by anakin87** [comment]
It would certainly be interesting...
Who knows if/when I will find the time to do it 😃 

If you have good resources about SPLADE, feel free to post them here!

**Comment by nickprock** [comment]
I also entered the tunnel of the posts of James Briggs 😅 

https://www.pinecone.io/learn/splade/
